# Generated by Django 5.2.8 on 2025-12-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('mdp', models.CharField(max_length=100)),
                ('direction', models.CharField(choices=[('DCSI', "Direction de la Communication et des Systèmes d'Information"), ('DAF', 'Direction Administrative et Financière'), ('DPSE', 'Direction de la Planification et du Suivi-Evaluation'), ('DAJC', 'Direction des Affaires Juridiques et du Contentieux'), ('DRH', 'Direction des Ressources Humaines'), ('DGGE', 'Direction Générale de la Gouvernance Environnementale'), ('DGDD', 'Direction Générale du Développement Durable'), ('ULC', 'Unité de Lutte contre la Corruption')], max_length=4)),
                ('role', models.CharField(choices=[('agent', 'Agent'), ('chef', 'Chef'), ('directeur', 'Directeur')], default='agent', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
    ]
