# Generated by Django 5.2.8 on 2025-12-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='created_at',
            new_name='cree_le',
        ),
        migrations.RenameField(
            model_name='mission',
            old_name='Date_depart',
            new_name='date_depart',
        ),
        migrations.RenameField(
            model_name='mission',
            old_name='Date_retour',
            new_name='date_retour',
        ),
        migrations.RenameField(
            model_name='mission',
            old_name='updated_at',
            new_name='modifie_le',
        ),
    ]
