# Generated by Django 5.2.8 on 2025-12-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_created_at_mission_cree_le_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='cree_par_nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
