# Generated by Django 5.2.8 on 2025-12-11 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mission_cree_par_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_responsables', to=settings.AUTH_USER_MODEL),
        ),
    ]
