# Generated by Django 5.2.8 on 2025-12-11 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mission_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='responsable',
        ),
        migrations.AddField(
            model_name='mission',
            name='destinataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_destinees', to=settings.AUTH_USER_MODEL),
        ),
    ]
