# Generated by Django 5.2.8 on 2025-12-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_mission_responsable_mission_destinataire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='destinataire',
        ),
    ]
