# Generated by Django 5.2.8 on 2025-12-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_mission_destinataire_nom_alter_agent_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Approuvée', 'Approuvée'), ('Rejetée', 'Rejetée')], max_length=20),
        ),
    ]
