# Generated by Django 5.2.8 on 2025-12-12 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_mission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='destinatairee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinatairee_missions', to=settings.AUTH_USER_MODEL),
        ),
    ]
