# Generated by Django 5.2.8 on 2025-12-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_mission_destinatairee'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='progression',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Terminée', 'Terminée')], default='En cours', editable=False, max_length=20),
        ),
    ]
