# Generated by Django 5.2.8 on 2026-01-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_mission_progression'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
