# Generated by Django 5.2.8 on 2026-01-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_agent_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='matricule',
            field=models.CharField(blank=True, default='pas de matricule', max_length=20, null=True, unique=True),
        ),
    ]
