# Generated by Django 5.2.8 on 2026-02-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_agent_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='superieur_hierarchique',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
